apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  name: machina-workspace-entain-bwin-app
  namespace: machina-workspace
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: machina-workspace-entain-bwin-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: machina-workspace-entain-bwin-app
    spec:
      containers:
      - command:
        - npm
        - start
        env:
        - name: NODE_ENV
          value: production
        image: machinasports/entain-bwin:latest
        imagePullPolicy: Always
        name: machina-workspace-entain-bwin-app
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/src/app/.ssh/machina_core_key
          name: machina-core-keys-volume
          readOnly: true
          subPath: machina_core_key
        - mountPath: /usr/src/app/.ssh/machina_core_key.pub
          name: machina-core-keys-volume
          readOnly: true
          subPath: machina_core_key.pub
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: dockerhub-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: user
        operator: Exists
      volumes:
      - name: machina-core-keys-volume
        secret:
          defaultMode: 420
          secretName: machina-core-key 