apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: tenant-otg-organization-ingress-tyltyhub-app
  namespace: tenant-otg-organization
spec:
  rules:
  - host: tyltyhub.machina.gg
    http:
      paths:
      - backend:
          service:
            name: tenant-otg-organization-tyltyhub-app
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - tyltyhub.machina.gg
    secretName: tyltyhub-tls 