apiVersion: v1
kind: Service
metadata:
  name: tenant-otg-organization-tyltyhub-app
  namespace: tenant-otg-organization
spec:
  clusterIP: 
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: tenant-otg-organization-tyltyhub-app
  sessionAffinity: None
  type: ClusterIP 