name: Build Development

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo " " >> .env
          echo "FEATURE_TOGGLE_ENABLE_AVATAR=0" >> .env
          echo " " >> .env
          echo "FEATURE_TOGGLE_ENABLE_BETS=0" >> .env
          echo " " >> .env
          echo "FEATURE_TOGGLE_ENABLE_CHAT=1" >> .env
          echo " " >> .env
          echo "MACHINA_API_KEY=${{ secrets.MACHINA_API_KEY }}" >> .env
          echo " " >> .env
          echo "MACHINA_CLIENT_URL=${{ vars.MACHINA_CLIENT_URL }}" >> .env
          echo " " >> .env
          echo "IMAGE_CONTAINER_ADDRESS=${{ vars.IMAGE_CONTAINER_ADDRESS }}" >> .env
          echo " " >> .env
          echo "NEXT_PUBLIC_GOOGLE_ANALYTICS_KEY=${{ secrets.NEXT_PUBLIC_GOOGLE_ANALYTICS_KEY }}" >> .env
          echo " " >> .env

      - name: Get version from package.json
        id: package_version
        run: echo "PACKAGE_VERSION=$(jq -r '.version' package.json)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.REGISTRY_URL }}/machina-sportingbet-cwc:${{ env.PACKAGE_VERSION }}
            ${{ secrets.REGISTRY_URL }}/machina-sportingbet-cwc:latest

      # - name: Notify Slack - Build Success
      #   uses: rtCamp/action-slack-notify@v2
      #   env:
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      #     SLACK_CHANNEL: your-slack-channel
      #     SLACK_USERNAME: GitHub Actions
      #     SLACK_COLOR: 'good'
      #     SLACK_TITLE: 'Build Successful'
      #     SLACK_MESSAGE: 'Build of machina-sportingbet-cwc:prod-${{ env.PACKAGE_VERSION }} finished successfully.'
      #     SLACK_ICON: ':heavy_check_mark:'
      #   if: success()
  
      # - name: Notify Slack - Build Failed
      #   uses: rtCamp/action-slack-notify@v2
      #   env:
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      #     SLACK_CHANNEL: your-slack-channel
      #     SLACK_USERNAME: GitHub Actions
      #     SLACK_COLOR: 'danger'
      #     SLACK_TITLE: 'Build Failed'
      #     SLACK_MESSAGE: 'Build of machina-sportingbet-cwc:prod-${{ env.PACKAGE_VERSION }} finished with errors.'
      #     SLACK_ICON: ':x:'
      #   if: failure()
      