name: Build SBOT

on:
  push:
    tags:
      - "v.sbot-*.*"

env:
  APP_NAME: entain-sbot
  MACHINA_API_KEY: ${{ secrets.SBOT_MACHINA_API_KEY }}
  MACHINA_CLIENT_URL: ${{ vars.SBOT_MACHINA_CLIENT_URL }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo " " >> .env
          echo "FEATURE_TOGGLE_ENABLE_AVATAR=0" >> .env
          echo " " >> .env
          echo "FEATURE_TOGGLE_ENABLE_BETS=0" >> .env
          echo " " >> .env
          echo "FEATURE_TOGGLE_ENABLE_CHAT=1" >> .env
          echo " " >> .env
          echo "MACHINA_API_KEY=${{ env.MACHINA_API_KEY }}" >> .env
          echo " " >> .env
          echo "MACHINA_CLIENT_URL=${{ env.MACHINA_CLIENT_URL }}" >> .env
          echo " " >> .env
          echo "IMAGE_CONTAINER_ADDRESS=${{ vars.IMAGE_CONTAINER_ADDRESS }}" >> .env
          echo " " >> .env
          echo "NEXT_PUBLIC_BRAND=sportingbet" >> .env
          echo " " >> .env
          echo "NEXT_PUBLIC_FEATURE_TOGGLE_LANGUAGE_SELECTED=br" >> .env
          echo " " >> .env
          echo "NEXT_PUBLIC_IMAGE_CONTAINER_ADDRESS=${{ vars.IMAGE_CONTAINER_ADDRESS }}" >> .env
          echo " " >> .env
          echo "NEXT_PUBLIC_SITE_OFFLINE=${{ vars.SBOT_SITE_OFFLINE }}" >> .env
          echo " " >> .env
          echo "NEXT_PUBLIC_GOOGLE_ANALYTICS_KEY=${{ secrets.NEXT_PUBLIC_GOOGLE_ANALYTICS_KEY }}" >> .env
          echo " " >> .env

      - name: Get tag name as release name
        run: echo "RELEASE_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.REGISTRY_URL }}/${{ env.APP_NAME }}:${{ env.RELEASE_NAME }}
