name: Release Production

on:
  push:
    tags:
      - "v.release-*.*"

env:
  AKS_CLUSTER_NAME: mks-community-cluster
  AKS_RESOURCE_GROUP: mks-community-group
  NAMESPACE: tenant-entain-organization
  APP_NAME: sportingbet-cwc
  DEPLOYMENT_NAME: sportingbet-cwc-prod
  MACHINA_API_KEY: ${{ secrets.PROD_MACHINA_API_KEY }}
  MACHINA_CLIENT_URL: ${{ vars.PROD_MACHINA_CLIENT_URL }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo " " >> .env
          echo "FEATURE_TOGGLE_ENABLE_AVATAR=1" >> .env
          echo " " >> .env
          echo "FEATURE_TOGGLE_ENABLE_BETS=1" >> .env
          echo " " >> .env
          echo "FEATURE_TOGGLE_ENABLE_CHAT=1" >> .env
          echo " " >> .env
          echo "MACHINA_API_KEY=${{ env.MACHINA_API_KEY }}" >> .env
          echo " " >> .env
          echo "MACHINA_CLIENT_URL=${{ env.MACHINA_CLIENT_URL }}" >> .env
          echo " " >> .env
          echo "IMAGE_CONTAINER_ADDRESS=${{ vars.IMAGE_CONTAINER_ADDRESS }}" >> .env
          echo " " >> .env
          echo "NEXT_PUBLIC_IMAGE_CONTAINER_ADDRESS=${{ vars.IMAGE_CONTAINER_ADDRESS }}" >> .env
          echo " " >> .env
          echo "NEXT_PUBLIC_GOOGLE_ANALYTICS_KEY=${{ secrets.NEXT_PUBLIC_GOOGLE_ANALYTICS_KEY }}" >> .env
          echo " " >> .env

      - name: Get tag name as release name
        run: echo "RELEASE_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Set branch name
        id: branch_name
        run: echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.REGISTRY_URL }}/${{ env.APP_NAME }}:${{ env.RELEASE_NAME }}

      - name: Notify Slack - Build Success
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: your-slack-channel
          SLACK_USERNAME: GitHub Actions
          SLACK_COLOR: 'good'
          SLACK_TITLE: 'Production Build Successful'
          SLACK_MESSAGE: 'Production build of ${{ env.APP_NAME }}:${{ env.RELEASE_NAME }} finished successfully.'
          SLACK_ICON: ':heavy_check_mark:'
        if: success()
  
      - name: Notify Slack - Build Failed
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: your-slack-channel
          SLACK_USERNAME: GitHub Actions
          SLACK_COLOR: 'danger'
          SLACK_TITLE: 'Production Build Failed'
          SLACK_MESSAGE: 'Production build of ${{ env.APP_NAME }}:${{ env.RELEASE_NAME }} finished with errors.'
          SLACK_ICON: ':x:'
        if: failure()

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS credentials
        uses: azure/aks-set-context@v3
        with:
          cluster-name: ${{ env.AKS_CLUSTER_NAME }}
          resource-group: ${{ env.AKS_RESOURCE_GROUP }}

      - name: Deploy to AKS
        run: |
          kubectl set image deployment/${{ env.DEPLOYMENT_NAME }} ${{ env.APP_NAME }}=${{ secrets.REGISTRY_URL }}/${{ env.APP_NAME }}:${{ env.RELEASE_NAME }} -n ${{ env.NAMESPACE }}
          kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }} -n ${{ env.NAMESPACE }}

      - name: Notify Slack - Deployment Success
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: your-slack-channel
          SLACK_USERNAME: GitHub Actions
          SLACK_COLOR: 'good'
          SLACK_TITLE: 'Production Deployment Successful'
          SLACK_MESSAGE: 'Production deployment of ${{ env.APP_NAME }}:${{ env.RELEASE_NAME }} completed successfully.'
          SLACK_ICON: ':rocket:'
        if: success()

      - name: Notify Slack - Deployment Failed
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: your-slack-channel
          SLACK_USERNAME: GitHub Actions
          SLACK_COLOR: 'danger'
          SLACK_TITLE: 'Production Deployment Failed'
          SLACK_MESSAGE: 'Production deployment of ${{ env.APP_NAME }}:${{ env.RELEASE_NAME }} failed.'
          SLACK_ICON: ':warning:'
        if: failure()
